server:
  port: ${port:8763}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/17611437257/springcloud
          search-paths:
          username:
          password: 
      label: master