server:
  port: ${port:8762}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: provider-log
  data:
    mongodb:
      port: 27017
      database: logs
