server:
  port: ${port:8762}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  mvc:
    view:
      prefix: /WEB-INF/JSP/
      suffix: .jsp
  application:
    name: provider-log
  data:
    mongodb:
      port: 27017
      database: logs
  datasource:
      url:  jdbc:mysql://localhost:3306/1708b?useUnicode=true&characterEncoding=utf-8
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: root
content:test